import { Metadata } from "next";
import React from "react";
import { promises as fs } from "fs";
import path from "path";
import { MDXRemote, compileMDX } from "next-mdx-remote/rsc";
import Link from "next/link";

type blogData = {
  title: string;
  description: string;
};

export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};
const Projects = async () => {
  const fileNames = await fs.readdir(
    path.join(process.cwd(), "src/content/blog")
  );
  // console.log("filenames", fileNames);

  const blogs = await Promise.all(
    fileNames.map(async (fileName) => {
      const content = await fs.readFile(
        path.join(process.cwd(), "src/content/blog", fileName),
        "utf-8"
      );
      // console.log(content);
      const { frontmatter } = await compileMDX<blogData>({
        source: content,
        options: {
          parseFrontmatter: true,
        },
      });
      return {
        fileName,
        slug: fileName.replace(/\.mdx$/, ""),
        ...frontmatter,
      };
    })
  );
  console.log(blogs);

  return (
    <div className="flex flex-col justify-center items-center min-h-screen max-w-5xl mx-auto p-4">
      Projects
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {blogs.map((blog) => (
          <Link
            href={`/projects/${blog.slug}`}
            key={blog.fileName}
            className="bg-gray-100 p-4 rounded-lg"
          >
            <h2 className="text-xl font-bold">{blog.title}</h2>
            <p>{blog.description}</p>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Projects;
